### ISSUE TITLE
MSI Afterburner Shared Memory Error Crash

### ISSUE THREAD

**Issue by tuxmelv** [Lacro59/playnite-gameactivity-plugin#11]
I'm having crashes. The only relevant logs during the time of the crash are pasted below immediately followed by an entry referencing startup of Playnite. Please advise if there is anything else required. MSI Afterburner is installed.

Loaded Extensions:
Game Activity
Statistics
Success Story

2020-07-28 13:25:15.9537|INFO:Started Space Engineers game.
2020-07-28 13:30:30.7638|ERROR:Unhandled exception occured.MSIAfterburnerNET.Common.Exceptions.SharedMemoryNotFoundException: Could not connect to MSI Afterburner shared memory. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at MSIAfterburnerNET.Common.SharedMemory.ReadonlyMemory..ctor(String name, FileMapAccess accessLevel)
   at MSIAfterburnerNET.HM.HardwareMonitor.OpenMemory()
   --- End of inner exception stack trace ---
   at MSIAfterburnerNET.HM.HardwareMonitor.OpenMemory()
   at MSIAfterburnerNET.HM.HardwareMonitor.RefreshHeader()
   at MSIAfterburnerNET.HM.HardwareMonitor.Refresh()
   at MSIAfterburnerNET.HM.HardwareMonitor..ctor()
   at GameActivity.GameActivity.<OnTimedEvent>d__66.MoveNext() in H:\Lacro59\playnite-gameactivity-plugin\GameActivity.cs:line 564
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
2020-07-28 20:50:41.7948|INFO:Application started from 'C:\Program Files\Playnite', with '' arguments.
2020-07-28 20:50:43.1160|INFO:PluginCommon - Parse plugin localization file C:\Users\<NAME>\AppData\Roaming\Playnite\Extensions\GameActivity_b969de3b0711c587c48960800bfd9bc0\localization\LocSource.xaml.
2020-07-28 20:50:43.1370|INFO:Loaded plugin: Game Activity
2020-07-28 20:50:43.1735|INFO:PluginCommon - Parse plugin localization file C:\Users\<NAME>\AppData\Roaming\Playnite\Extensions\Statistics_ca512b8608887b13804fca36507f5a46\localization\LocSource.xaml.
2020-07-28 20:50:43.1735|INFO:Loaded plugin: Statistics
2020-07-28 20:50:43.2515|INFO:PluginCommon - Parse plugin localization file C:\Users\<NAME>\AppData\Roaming\Playnite\Extensions\SuccessStory_e19bcf3b4090d027d90f39ef7ff733f3\localization\LocSource.xaml.
2020-07-28 20:50:43.2670|INFO:Loaded plugin: Success Story
2020-07-28 20:50:43.3145|INFO:Loaded plugin: Amazon Games Library Importer
2020-07-28 20:50:43.3590|INFO:Loaded plugin: Battle.net Library Importer
2020-07-28 20:50:43.4030|INFO:Loaded plugin: GOG Library Importer
2020-07-28 20:50:43.4345|INFO:Loaded plugin: Humble Library Importer
2020-07-28 20:50:43.4805|INFO:Loaded plugin: IGDB metadata provider
2020-07-28 20:50:43.5685|INFO:Loaded plugin: itch.io Library Importer
2020-07-28 20:50:43.6645|INFO:Loaded plugin: Steam Library Importer
2020-07-28 20:50:43.7025|INFO:Loaded plugin: Twitch Library Importer
2020-07-28 20:50:43.7535|INFO:Loaded plugin: Universal Steam Metadata
2020-07-28 20:50:43.8260|INFO:Loaded plugin: Uplay Library Importer
2020-07-28 20:50:43.8695|INFO:Loaded plugin: Xbox Library Importer

**Comment by Lacro59** [comment]
Is Msi Afterburner and RivaTuner Statistics Server running?
![image](https://user-images.githubusercontent.com/124054/89099170-a197a000-d3ed-11ea-9ade-dec7892bfe05.png)

**Comment by tuxmelv** [comment]
MSI was but I am unsure if RivaTuner was running. I'll try it again making sure those 2 apps are explicitly running. Thank you.

**Comment by Lacro59** [comment]
I will add a notification when Msi Afterburner is not run and that options is activated.
