### ISSUE TITLE
 Error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mainmango** [Lacro59/playnite-gameactivity-plugin#123]
Hi,

Plugin is giving the following error. Tried re-installing and deleting the data folder but issue still persists.

Any suggestions?

09-03 22:25:50.663|ERROR|ExtensionFactory:Failed to execute OnGameStarted method from GameActivity plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at GameActivity.GameActivity.OnGameStarted(OnGameStartedEventArgs args) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs:line 1029
   at Playnite.Plugins.ExtensionFactory.Controllers_Started(Object sender, GameStartedEventArgs args) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 617

**Comment by mainmango** [comment]
Playnite still giving me the same error but this is the error log. Not sure if it's something different now.

11-03 08:10:45.441|ERROR|GameActivity#Common:Error on OnGameStarted()|D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs|1058
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsShared.LocalSystem..ctor(String ConfigurationsPath, Boolean WithDiskInfos) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\LocalSystem.cs:line 40
   at GameActivity.Services.ActivityDatabase.get_LocalSystem() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Services\ActivityDatabase.cs:line 24
   at GameActivity.GameActivity.OnGameStarted(OnGameStartedEventArgs args) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs:line 1058
