### ISSUE TITLE
Plugin crashes on start after updating to Playnite 10.0

### ISSUE THREAD

**Issue by Tholdorin** [Lacro59/playnite-gameactivity-plugin#162]
Hi

After updating to Playnite 10.0 I receive the following error message when starting Playnite:
Extension "GameActivity" failed to load properly.

When I look into the "playnite.log" file I can see the following error logs:
```
15-09 21:24:39.118|ERROR|ExtensionFactory:Failed to load plugin: GameActivity
15-09 21:24:39.118|ERROR|ExtensionFactory:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Playnite.Plugins.ExtensionFactory.<LoadPlugins>d__33.MoveNext() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 449
   at Playnite.Plugins.ExtensionFactory.LoadPlugins(List`1 ignoreList, Boolean builtInOnly, List`1 externals) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 409
15-09 21:24:39.141|ERROR|ExtensionFactory:
System.TypeLoadException: Method 'BufferedUpdate' in type 'CommonPlayniteShared.Database.ItemCollection`1' from assembly 'GameActivity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Not sure if this would be relevant but the exact same issue is happening for other Extensions as well (HowLongToBeat, PlayerActivities and SuccessStory).

**Comment by Skylin3r** [comment]
same issue, updated today to Playnite 10.1, getting Extension failed to load properly.

**Comment by lordscales91** [comment]
I just uninstalled Playnite and installed the old version as a workaround https://github.com/JosefNemec/Playnite/releases/tag/9.19

**Comment by Lacro59** [comment]
fixed with the last release
