### ISSUE TITLE
Error: GameActivity: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by LT3Dave** [Lacro59/playnite-gameactivity-plugin#192]
Hoping to find a solution to this problem. Happy to supply more logs as needed. Snippet of the Error is below. Error occurs when trying to look at the GameActivity List page, no games end up showing. Not sure what's causing it.
```
27-05 12:24:12.968|ERROR|GameActivity#Common:Error on getActivityByListGame()|D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Views\GameActivityView.xaml.cs|887
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsShared.LocalSystem..ctor(String ConfigurationsPath, Boolean WithDiskInfos) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\LocalSystem.cs:line 47
   at GameActivity.Services.ActivityDatabase.get_LocalSystem() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Services\ActivityDatabase.cs:line 24
   at GameActivity.Models.Activity.get_Configuration() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Models\Activity.cs:line 47
   at GameActivity.Views.GameActivityView.getActivityByListGame() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Views\GameActivityView.xaml.cs:line 887
```

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/6e6e7afdb31cf2d42fc37ae2ff5b8d6384143bfb
