### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Romarain** [Lacro59/playnite-gameactivity-plugin#26]
After playing Starcraft II, Playnite poped up an error message indicating that GameActivity has crashed.
After restarting Playnite, everything seems fine and yesterday I played another without problems.

In attachment, the log.

[GameActivity_bug.txt](https://github.com/Lacro59/playnite-gameactivity-plugin/files/5721212/GameActivity_bug.txt)

**Comment by Lacro59** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PluginCommon.PlayniteUiHelper.OnBtActionBarToggleButtonClick(Object sender, RoutedEventArgs e) in H:\GitHub\Lacro59\playnite-gameactivity-plugin\playnite-plugincommon\IntegrationUI.cs:line 354
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
```

**Comment by Romarain** [comment]
Last updates fixe the problem, I close.
